name: C4GT Beginner Ticket
description: Create a new Ticket for C4GT Community
title: "[C4GT Community]: "
labels: ["C4GT Community"]
body:
  - type: textarea
    id: ticket-description
    validations:
      required: true
    attributes:
      label: Ticket Contents
      value: |
        ## Description
        Please provide the following basic details to help us understand your background and context better.
          - **Name:**
          - **GitHub Username:**
          - **LinkedIn Profile:**
          - **College/University:**
          _If you feel comfortable, you can also provide additional information such as your area of expertise or any specific information you'd like to share._


  - type: textarea
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: Goals
      description: List the goals of the feature.
      value: |
        ## Goals
        - [ ] Adding your basic details

  - type: textarea
    id: ticket-expected-outcome
    attributes:
      label: Expected Outcome
      description: Describe in detail what the final product or result should look like and how it should behave.

  - type: textarea
    id: ticket-acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria for this feature.

  - type: textarea
    id: ticket-implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      description: List any technical details about the proposed implementation, including any specific technologies that will be used.
      value: |
         To implement the changes in the `Community.md` file on the GitHub repository (https://github.com/Code4GovTech/C4GT/blob/main/Community.md), follow these steps:
          1. **Fork the Repository:**
            - Visit the repository (https://github.com/Code4GovTech/C4GT).
            - Click the "Fork" button in the upper right corner to create a fork of the repository in your GitHub account.
          2. **Clone Your Fork:**
            - Open a terminal or command prompt.
            - Run the following command to clone your fork to your local machine:
             ```bash
                git clone https://github.com/your-username/C4GT.git
             ```
          3. **Navigate to the Repository:**
            - Change into the repository directory:
             ```bash
                cd C4GT
             ```
          4. **Edit the Community.md File:**
            - Open the `Community.md` file in a text editor. You can use any code editor or a simple text editor.
            - Locate the existing table and replace the details with your own:
            ```markdown
                 <table>
                   <tr>
                     <td>Name</td>
                     <td>Your Name</td>
                   </tr>
                   <tr>
                     <td>GitHub</td>
                     <td>https://github.com/your-username</td>
                   </tr>
                   <tr>
                     <td>LinkedIn</td>
                     <td>https://www.linkedin.com/in/your-linkedin</td>
                   </tr>
                   <tr>
                     <td>College</td>
                     <td>Your College/University</td>
                   </tr>
               </table>
             ```
           5. **Save Changes:**
             - Save the changes to the `Community.md` file.
           6. **Commit Changes:**
             - In the terminal, run the following commands to commit the changes:
             ```bash
               git add Community.md
               git commit -m "Update my details in Community.md"
             ```
           7. **Push Changes to Your Fork:**
           - Push the changes to your GitHub fork:
             ```bash
                git push origin main
             ```
           8. **Create a Pull Request:**
             - Visit your fork on GitHub (https://github.com/your-username/C4GT).
             - Click on the "New pull request" button.
             - Ensure the base repository is `Code4GovTech/C4GT` and the base branch is `main`.
             - Ensure the head repository is your fork and the compare branch is `main`.
             - Click "Create pull request" and provide a meaningful title and description.
             - Click "Create pull request" again to submit the pull request.
        Your changes will now be submitted as a pull request to the original repository, and the maintainers can review and merge them.


  - type: textarea
    id: ticket-mockups
    attributes:
      label: Mockups/Wireframes
      description: Include links to any visual aids, mockups, wireframes, or diagrams that help illustrate what the final product should look like. This is not always necessary, but can be very helpful in many cases.

  - type: input
    id: ticket-product
    attributes:
      label: Product Name
      placeholder: Enter Product Name
    validations:
      required: true

  - type: dropdown
    id: ticket-organisation
    attributes:
      label: Organisation Name
      description: Enter Organisation Name
      multiple: false
      options:
        - C4GT
        - Dhiway
        - FIDE
        - SamagraX
        - ShikshaLokam
        - Tech4Dev
        - Tibil
    validations:
      required: true

  - type: input
    id: ticket-governance-domain
    attributes:
      label: Domain
      placeholder: Enter Area of Governance

  - type: dropdown
    id: ticket-technical-skills-required
    attributes:
      label: Tech Skills Needed
      description: Select the technologies needed for this ticket (use Ctrl or Command to select multiple)
      multiple: true
      options:
        - .NET
        - Agile
        - Angular
        - Artificial Intelligence
        - ASP.NET
        - AWS
        - Babel
        - Bootstrap
        - C#
        - Chart.js
        - CI/CD
        - Computer Vision
        - CORS
        - cURL
        - Cypress
        - D3.js
        - Database
        - Debugging
        - Design
        - DevOps
        - Django
        - Docker
        - Electron
        - ESLint
        - Express.js
        - Feature
        - Flask
        - Go
        - GraphQL
        - HTML
        - Ionic
        - Jest
        - Java
        - JavaScript
        - Jenkins
        - JWT
        - Kubernetes
        - Laravel
        - Machine Learning
        - Maintenance
        - Markdown
        - Material-UI
        - Microservices
        - MongoDB
        - Mobile
        - Mockups
        - Mocha
        - Natural Language Processing
        - NestJS
        - Node.js
        - NUnit
        - OAuth
        - Performance Improvement
        - Prettier
        - Python
        - Question
        - React
        - React Native
        - Redux
        - RESTful APIs
        - Ruby
        - Ruby on Rails
        - Rust
        - Scala
        - Security
        - Selenium
        - SEO
        - Serverless
        - Solidity
        - Spring Boot
        - SQL
        - Swagger
        - Tailwind CSS
        - Test
        - Testing Library
        - Three.js
        - TypeScript
        - UI/UX/Design
        - Virtual Reality
        - Vue.js
        - WebSockets
        - Webpack
        - Other
    validations:
      required: true

  - type: textarea
    id: ticket-mentors
    attributes:
      label: Mentor(s)
      description: Please tag relevant mentors for the ticket
    validations:
      required: true

  - type: dropdown
    id: ticket-complexity
    attributes: 
      label: Complexity
      description: Choose a complexity describing the complexity of your ticket
      multiple: false
      options:
        - Beginner
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: dropdown
    id: ticket-category
    attributes: 
      label: Category
      description: Choose the categories that best describe your ticket
      multiple: true
      options:
        - API
        - Analytics
        - Accessibility
        - Backend
        - Breaking Change
        - Beginner Friendly
        - Configuration
        - CI/CD
        - Database
        - Data Science
        - Deprecation
        - Documentation
        - Delpoyment
        - Frontend
        - Internationalization
        - Localization
        - Machine Learning
        - Maintenance
        - Mobile
        - Performance Improvement
        - Question
        - Refactoring
        - Research
        - Needs Reproduction
        - SEO
        - Security
        - Testing
        - Other
    validations:
      required: true

  
